config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'invoices#index', as: :invoice_index

  devise_for :users

  resources :users
  resources :invoices

  get 'my_invoices' => 'invoices#my_invoices', as: :my_invoices
  get 'invoice_qr_code/:id' => 'invoices#invoice_qr_code', as: :invoice_qr_code
  post 'upload_zip_file' => 'invoices#upload_zip_file', as: :upload_zip_file
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  INVOICE_STATUSES = ['ACTIVE', 'VOID', 'PAID', 'NOT PAID']
  INVOICE_TYPES = ['ALL','RECEIVED', 'EMITTED']

  validate :emitter_and_receiver_difference
  validates_uniqueness_of :invoice_uid
  validates_presence_of :invoice_uid

  belongs_to :emitter, class_name: 'User', foreign_key: :emitter_id
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id

  delegate :name, to: :emitter, prefix: true
  delegate :name, to: :receiver, prefix: true

  scope :f_by_status, ->(status) { where(status: status) if status.present?}
  scope :f_by_emitter, ->(emitter) { includes(:emitter).where(emitter: emitter) if emitter.present?}
  scope :f_by_receiver, ->(receiver) { includes(:emitter).where(receiver: receiver) if receiver.present?}
  scope :f_by_min_emitted_at, ->(min_emitted_at) { where(emitted_at: min_emitted_at..) if min_emitted_at.present?}
  scope :f_by_max_emitted_at, ->(max_emitted_at) { where(emitted_at: ..max_emitted_at) if max_emitted_at.present?}
  scope :f_by_type, ->(type, user_id) {
    if type == 'RECEIVED'
      where(receiver: user_id)
    elsif type == 'EMITTED'
      where(emitter: user_id)
    end
  }
  scope :min_amount, ->(min) { where(amount_cents: min..) if min.present?}
  scope :max_amount, ->(max) { where(amount_cents: ..max) if max.present?}

  def emitter_and_receiver_difference
    if self.emitter_id == self.receiver_id
      errors.add(:emitter_id, 'must be different to receiver')
      errors.add(:receiver_id, 'must be different to emitter')
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  require 'zip'

  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices
  def index
    if params[:filters].present?
      filters     = params[:filters]
      @status     = filters['status']
      @emitter    = filters['emitter']
      @receiver   = filters['receiver']
      @range_min  = filters['amount_range_min']
      @range_max  = filters['amount_range_max']

      @invoices = Invoice.f_by_status(@status).f_by_emitter(@emitter).f_by_receiver(@receiver).min_amount(@range_min).max_amount(@range_max)
      @invoices = @invoices.paginate(:page => params[:page], :per_page => 30)
    else
      @invoices = Invoice.all.paginate(:page => params[:page], :per_page => 30)
    end
  end

  # GET /invoices/1
  def show
  end

  # GET /users/new
  def new
    @invoice = Invoice.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /invoices
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoices_path, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoices_path, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_invoices
    if params[:filters].present?
      filters = params[:filters]
      @invoice_type = filters['invoice_type']
      @start_date   = Date.civil(filters["min_emitted_at(1i)"].to_i,
                               filters["min_emitted_at(2i)"].to_i,
                               filters["min_emitted_at(3i)"].to_i)

      @end_date = Date.civil(filters["max_emitted_at(1i)"].to_i,
                             filters["max_emitted_at(2i)"].to_i,
                             filters["max_emitted_at(3i)"].to_i)
      @invoices = Invoice.f_by_type(@invoice_type, current_user.id).f_by_min_emitted_at(@start_date).f_by_max_emitted_at(@end_date)
      @invoices = @invoices.paginate(:page => params[:page], :per_page => 30)
    else
      @invoices = Invoice.where(emitter: current_user.id).or(Invoice.where(receiver: current_user.id)).paginate(:page => params[:page], :per_page => 30)
    end
  end

  def upload_zip_file
    if params[:zip_file].present?
      SaveInvoicesWorker.perform_async(params[:zip_file].tempfile.path)
    end
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoices in process, don't close this window.... please refresh later." }
      format.json { head :no_content }
    end
  end

  def invoice_qr_code
    @invoice = Invoice.find(params[:id])
    @qr_code = RQRCode::QRCode.new(@invoice.try(:cfdi_digital_stamp))
    @svg = @qr_code.as_svg(
                       offset: 0,
                       color: '000',
                       shape_rendering: 'cripsEdges',
                       module_size: 6
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:invoice_uid, :status, :emitter_id, :receiver_id, :amount_cents, :amount_currency, :emitted_at, :expires_at, :signed_at, :cfdi_digital_stamp)
    end
end

app/views/invoices/_form.html.erb
<%= form_for invoice do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :invoice_uid %>
    <%= form.text_field :invoice_uid %>
  </div>

  <div class="input-field">
    <%= form.label :status %>
    <%= form.select :status, Invoice::INVOICE_STATUSES.map { |s| [s] }, {}, {class: "simple-select"}%>
  </div>

  <div class="input-field">
    <%= form.label :emitter_id %>
    <%= form.select :emitter_id, User.all.collect{|u| [u.name, u.id]}, {}, {class: "simple-select"}%>
  </div>

  <div class="input-field">
    <%= form.label :receiver_id %>
    <%= form.select :receiver_id, User.all.collect{|u| [u.name, u.id]}, {}, {class: "simple-select"}%>
  </div>

  <div class="input-field">
    <%= form.label :amount_cents %>
    <%= form.number_field :amount_cents %>
  </div>

  <div class="input-field">
    <%= form.label :amount_currency %>
    <%= form.text_field :amount_currency %>
  </div>

  <div class="input-field">
    <%= form.label :emitted_at %>
    <div class="date-select">
      <%= form.date_select :emitted_at %>
    </div>
  </div>

  <div class="input-field">
    <%= form.label :expires_at %>
    <div class="date-select">
      <%= form.date_select :expires_at %>
    </div>
  </div>

  <div class="input-field">
    <%= form.label :signed_at %>
    <div class="date-select">
      <%= form.date_select :signed_at %>
    </div>
  </div>

  <div class="input-field">
    <%= form.label :cfdi_digital_stamp %>
    <%= form.text_field :cfdi_digital_stamp %>
  </div>

  <div class="form-actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<div class="content-container">
  <a href="/invoices" class="goBack">< Invoices</a>

  <div class="form">
    <h1>Editing Invoice</h1>

    <%= render 'form', invoice: @invoice %>

    <%= link_to 'Show', @invoice %> |
    <%= link_to 'Back', invoices_path %>
  </div>
</div>

app/views/invoices/index.html.erb
<div class="content-container">

  <h1>Invoices</h1>
  <span><strong><%= @invoices.count %> Invoices</strong></span>

  <div class="content-subhead">
    <div>
      <%= form_tag(invoices_path, method: :get) do %>
        <span>Filter</span>
        <div>
          <div class="filter-input">
            <span>
              Status:
            </span>
            <%= select :filters, :status, Invoice::INVOICE_STATUSES.map { |s| [s] }, include_blank: true, selected: @status.present? ? @status : nil %>
          </div>
          <div>
            <div class="filter-input">
              <span>
                Emitter:
              </span>
              <%= select :filters, :emitter, User.all.collect{|u| [u.name, u.id]}, include_blank: true, selected: @emitter.present? ? @emitter : nil  %>
            </div>
          </div>
          <div>
            <div class="filter-input">
              <span>
                Receiver:
              </span>
              <%= select :filters, :receiver, User.all.collect{|u| [u.name, u.id]}, include_blank: true, selected: @receiver.present? ? @receiver : nil   %>
            </div>
          </div>
          <div>
            Amount Range from <%= text_field :filters, :amount_range_min, value: @range_min.present? ? @range_min : nil %>
            to <%= text_field :filters, :amount_range_max, value: @range_max.present? ? @range_max : nil %>
          </div>
          <div class="filter-buttons">
            <a href="/invoices" class="filter-btn-outline">Clear</a>
            <%= submit_tag "Search", class:"filter-btn"%>
          </div>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-between flex-column">
      <div class="zip-upload-container">
        <span class="h4"><strong>Create Invoices with ZIP:</strong></span>
        <%= form_tag upload_zip_file_path, method: :post, multipart: true do %>
          <%= label_tag 'ZIP file', 'Select ZIP archive' %>
          <%= file_field_tag 'zip_file' %>

          <%= submit_tag 'Submit' %>
        <% end %>
      </div>

      <div class="d-flex justify-content-between">
        <a href="<%= my_invoices_path %>" tager="_blank" class="filter-btn">
          My Invoices
        </a>
        <%= link_to 'New Invoice +', new_invoice_path, class:"filter-btn" %>
      </div>
    </div>
  </div>


  <table>
    <thead>
    <tr>
      <th>Invoice uid</th>
      <th>Status</th>
      <th>Emitter</th>
      <th>Receiver</th>
      <th>Amount cents</th>
      <th>Amount currency</th>
      <th>Emitted at</th>
      <th>Expires at</th>
      <th>Signed at</th>
      <th>Cfdi digital stamp</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.invoice_uid %></td>
        <td><%= invoice.status %></td>
        <td><%= invoice.emitter_name %></td>
        <td><%= invoice.receiver_name %></td>
        <td><%= invoice.amount_cents %></td>
        <td><%= invoice.amount_currency %></td>
        <td><%= invoice.emitted_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
        <td><%= invoice.expires_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
        <td><%= invoice.signed_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
        <td><a href="<%= invoice_qr_code_path(invoice.id) %>">QR</a></td>
        <td>
          <%= link_to 'Show', invoice %>
          <%= link_to 'Edit', edit_invoice_path(invoice) %>
          <%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= will_paginate @invoices, renderer: BootstrapPagination::Rails, next_label: "Siguiente", previous_label: "Anterior" %>

</div>

app/views/invoices/invoice_qr_code.html.erb
<div class="content-container">
  <a href="/invoices" class="goBack">< Invoices</a>

  <h1>Cfdi digital stamp</h1>
  <%= @svg.html_safe  %>
</div>

app/views/invoices/my_invoices.html.erb
<div class="content-container">
    <a href="/invoices" class="goBack">< Invoices</a>
    <h1>Invoices</h1>
    <span><strong><%= @invoices.count %> Invoices</strong></span>

    <div class="content-subhead">
      <div>
        <%= form_tag(my_invoices_path, method: :get) do %>
          <span>Filter</span>
          <div class="filter-input">
            <span style="width: 115px !important;">
              Invoice Type:
            </span>
            <%= select :filters, :invoice_type, Invoice::INVOICE_TYPES.map { |s| [s] }, {selected: @invoice_type}, {class: "select-lg"}  %>
          </div>
          <div>
            Issue Date from <%= date_select :filters, :min_emitted_at, default: -1.year.from_now, selected: @start_date.present? ? @start_date : nil %>
            to
            <%= date_select :filters, :max_emitted_at, selected: @end_date.present? ? @end_date : nil %>
          </div>

          <div class="filter-buttons">
            <a href="/my_invoices" class="filter-btn-outline">Clear</a>
            <%= submit_tag "Search", class:"filter-btn"%>
          </div>
        <% end %>
      </div>
    </div>


    <table >
      <thead>
      <tr>
        <th>Invoice uid</th>
        <th>Status</th>
        <th>Emitter</th>
        <th>Receiver</th>
        <th>Amount cents</th>
        <th>Amount currency</th>
        <th>Emitted at</th>
        <th>Expires at</th>
        <th>Signed at</th>
        <th>Cfdi digital stamp</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.invoice_uid %></td>
          <td><%= invoice.status %></td>
          <td><%= invoice.emitter_name %></td>
          <td><%= invoice.receiver_name %></td>
          <td><%= invoice.amount_cents %></td>
          <td><%= invoice.amount_currency %></td>
          <td><%= invoice.emitted_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
          <td><%= invoice.expires_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
          <td><%= invoice.signed_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
          <td><a href="<%= invoice_qr_code_path(invoice.id) %>">QR</a></td>
          <td><%= link_to 'Show', invoice %></td>
          <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
          <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <%= will_paginate @invoices, renderer: BootstrapPagination::Rails, next_label: "Siguiente", previous_label: "Anterior" %>
</div>

app/views/invoices/new.html.erb
<div class="content-container">
  <a href="/invoices" class="goBack">< Invoices</a>

  <div class="form">

    <h1>New Invoice</h1>

    <%= render 'form', invoice: @invoice %>

    <div class="d-flex justify-content-center">
      <%= link_to 'Back', invoices_path %>
    </div>

  </div>
</div>

app/views/invoices/show.html.erb
<div class="content-container">
  <a href="/invoices" class="goBack">< Invoices</a>

  <div style="max-width: 500px; margin-top: 100px; word-wrap:break-word;">
    <p>
      <strong>Invoice uid:</strong>
      <%= @invoice.invoice_uid %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @invoice.status %>
    </p>

    <p>
      <strong>Emitter:</strong>
      <%= @invoice.emitter_id %>
    </p>

    <p>
      <strong>Receiver:</strong>
      <%= @invoice.receiver_id %>
    </p>

    <p>
      <strong>Amount cents:</strong>
      <%= @invoice.amount_cents %>
    </p>

    <p>
      <strong>Amount currency:</strong>
      <%= @invoice.amount_currency %>
    </p>

    <p>
      <strong>Emitted at:</strong>
      <%= @invoice.emitted_at %>
    </p>

    <p>
      <strong>Expires at:</strong>
      <%= @invoice.expires_at %>
    </p>

    <p>
      <strong>Signed at:</strong>
      <%= @invoice.signed_at %>
    </p>

    <p>
      <strong>Cfdi digital stamp:</strong>
      <%= @invoice.cfdi_digital_stamp %>
    </p>
  </div>

  <div class="d-flex justify-content-between" style="width: 200px;">
    <%= link_to 'Edit', edit_invoice_path(@invoice) %> |
    <%= link_to 'Back', invoices_path %>

  </div>

</div>